### ISSUE TITLE
LVGL

### ISSUE THREAD

**Issue by tyeth** [liangyingy/lcd_binding_micropython#1]
Hi, I wanted to use lvgl and the T-DisplayS3 in micropython. How complex is that, having read a bit I think I would need the driver here or your modified esp_lcd  setup to link to the  lvgl_micropython binding and then include lvgl plus conf from t-displays3 repo. 
 It looks like support for the S2/S3 in lvgl_esp32_drivers and lvgl >7 will come soon so this may not be worth pursuing yet. This is an issue to see an example added to the repo that includes lvgl.

**Comment by lbuque** [comment]
https://github.com/lvgl/lv_binding_micropython/issues/227
