### ISSUE TITLE
Precompiled binaries?

### ISSUE THREAD

**Issue by Sebbb** [liangyingy/lcd_binding_micropython#3]
Hello,

would it be possible to provide precompiled binaries for Micropython including the binding for ESP32-S3, the platform of the current T-Display-S3-AMOLEDs, preferably based on Micropython 1.20.0?

Thanks,
Sebastian

**Comment by lbuque** [comment]
@Sebbb I try to compile the firmware with micropython 1.20 and it fails.

I need to modify the code, I need to find time to modify the code.

Also, I've left LILYGO and don't have the T-Display-S3-AMOLED on hand, so I can't verify if the firmware works.

**Comment by Sebbb** [comment]
Hey,

ah, okay.. I also tried to compile it and failed, but then I know the reason... :D

If you still want to support this and modify the code, I have a T-Display-S3-AMOLEDs and could test if it works fine.

Sebastian

**Comment by lbuque** [comment]
@Sebbb I compiled a firmware, you can verify that it works.

[LILYGO_T-DisplayS3-AMOLED-c1.20.0.zip](https://github.com/lbuque/lcd_binding_micropython/files/11410995/LILYGO_T-DisplayS3-AMOLED-c1.20.0.zip)

**Comment by Sebbb** [comment]
That was fast! :D

I just tried color_loop.py, works well :)

![image](https://user-images.githubusercontent.com/4967941/236594373-c8bbe1a9-2acb-4090-836a-fa72ad68b049.png)

Thanks!

**Comment by Sebbb** [comment]
Hey, could you maybe push your changes that made it compatible with Micropython 1.20.0 to the repo? Then I can try to compile it myself for upcoming versions :)

Thanks!

**Comment by lbuque** [comment]
@Sebbb updated code
