### ISSUE TITLE
Compile error `esp_lcd_panel_io.h`

### ISSUE THREAD

**Issue by CatMeowByte** [liangyingy/lcd_binding_micropython#5]
ESP-IDF: 5.0.2
Micropython: Master (1.20)

Compilation terminated with following error:
```
/module/lcd/hal/esp32/esp32.c:10:10: fatal error: esp_lcd_panel_io.h: No such file or directory
   10 | #include "esp_lcd_panel_io.h"
      |          ^~~~~~~~~~~~~~~~~~~~
```

Turns out it has been mentioned in #4,
and now for the new Micropython version it's moved to `/ports/esp32/esp32_common.cmake`.
I suggest to update the documentation and add an important instruction to tell user for it.

**Comment by lbuque** [comment]
Please refer to #4

**Comment by lbuque** [comment]
Thanks, I'll update the docs later.
